# Generated by Django 3.2.4 on 2021-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NSECalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openInterest', models.IntegerField(blank=True, max_length=20, null=True)),
                ('changeinOpenInterest', models.IntegerField(blank=True, max_length=20, null=True)),
                ('totalTradedVolume', models.IntegerField(blank=True, max_length=20, null=True)),
                ('impliedVolatility', models.FloatField(blank=True, max_length=10, null=True)),
                ('lastPrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('change', models.FloatField(blank=True, max_length=20, null=True)),
                ('bidQty', models.IntegerField(blank=True, max_length=20, null=True)),
                ('bidprice', models.FloatField(blank=True, max_length=20, null=True)),
                ('askPrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('askQty', models.IntegerField(blank=True, max_length=20, null=True)),
                ('strikePrice', models.FloatField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NSEPuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('bidQty', models.IntegerField(blank=True, max_length=20, null=True)),
                ('bidprice', models.FloatField(blank=True, max_length=20, null=True)),
                ('askPrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('askQty', models.IntegerField(blank=True, max_length=20, null=True)),
                ('change', models.FloatField(blank=True, max_length=20, null=True)),
                ('lastPrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('impliedVolatility', models.FloatField(blank=True, max_length=10, null=True)),
                ('totalTradedVolume', models.IntegerField(blank=True, max_length=20, null=True)),
                ('changeinOpenInterest', models.IntegerField(blank=True, max_length=20, null=True)),
                ('openInterest', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
