# Generated by Django 3.2.4 on 2021-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nseindiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsecalls',
            name='askQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsecalls',
            name='bidQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsecalls',
            name='changeinOpenInterest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsecalls',
            name='openInterest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsecalls',
            name='totalTradedVolume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nseputs',
            name='askQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nseputs',
            name='bidQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nseputs',
            name='changeinOpenInterest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nseputs',
            name='openInterest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nseputs',
            name='totalTradedVolume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
