# Generated by Django 3.2.4 on 2021-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nseindiaApp', '0002_auto_20210611_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('expiryDate', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
