# Generated by Django 3.2.4 on 2021-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nseindiaApp', '0003_stockdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockDetail',
        ),
        migrations.AddField(
            model_name='nsecalls',
            name='expiryDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nseputs',
            name='expiryDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
